import turtle
import random
screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('wheat2')

#ground is on the ground
t_ground = turtle.Turtle()
t_ground.penup()
t_ground.pencolor('wheat4')
t_ground.fillcolor('wheat4')
t_ground.speed(0)
t_ground.goto(-1000,-100)
t_ground.pendown()
t_ground.begin_fill()
t_ground.goto(1000,-100)
t_ground.goto(1000,-1000)
t_ground.goto(-1000,-1000)
t_ground.goto(-1000,-100)
t_ground.end_fill()

#rug on the ground
t = turtle.Turtle()

t.penup()
t.goto(-250,-200)
t.pensize(20)
t.pencolor('white')
t.fillcolor('white')
t.pendown()
t.begin_fill()
t.forward(500)
t.right(90)
t.forward(250)
t.right(90)
t.forward(500)
t.right(90)
t.forward(250)
t.right(90)
t.forward(250)
t.right(90)
t.end_fill()
t.goto(-250,-201)
t.fillcolor('white')
t.speed(10)
t.penup()
t.goto(-250,-190)
t.pendown()
t.setheading(0)
t.pensize(2)
t.pencolor('white')
t.forward(500)
t.penup()

#tree other wide of the window
t_tree = turtle.Turtle()
t_tree.speed(0)
t_tree.penup()
t_tree.goto(200,100)
t_tree.pendown()
t_tree.pensize(15)
t_tree.pencolor('saddleBrown')

t_tree.goto(200,-200)
t_tree.pensize(1)

t_tree.penup()
t_tree.fillcolor('DarkOliveGreen4')
t_tree.goto(200,150) #middle
t_tree.pendown()
t_tree.begin_fill()

t_tree.goto(100,-150)
t_tree.goto(300,-150)
t_tree.goto(200,150) #middle
t_tree.end_fill()

t_tree.penup()
t_tree.fillcolor('gold')
t_tree.goto(190,125)
t_tree.pendown()
t_tree.begin_fill()
t_tree.goto(200,170)
t_tree.goto(210,125)
t_tree.goto(180,150)
t_tree.goto(220,150)
t_tree.goto(190,125)

t_tree.end_fill()


#window
window_turtle = turtle.Turtle()

window_turtle.penup()
window_turtle.goto(-200, 100)
window_turtle.pendown()
window_turtle.pensize(3)
window_turtle.pencolor("black")
window_turtle.fillcolor('lightsteelblue')
window_turtle.begin_fill()
window_turtle.goto(0, 100)
window_turtle.goto(0, 300)
window_turtle.goto(-200, 300)
window_turtle.goto(-200, 100)
window_turtle.end_fill()
window_turtle.pencolor('snow1')

for i in range(40):
    x = random.randint(-190,-10)
    y = random.randint(110,290)
    window_turtle.penup()
    window_turtle.goto(x,y)
    window_turtle.pendown()
    z = random.randint(1,3)
    window_turtle.pensize(z)
    window_turtle.dot()

window_turtle.pencolor('black')
window_turtle.penup()
window_turtle.goto(-100,100)
window_turtle.pendown()
window_turtle.goto(-100,300)

window_turtle.penup()
window_turtle.goto(0,200)
window_turtle.pendown()
window_turtle.goto(-200,200)

#presents
window_turtle.penup()
window_turtle.goto(-200, -200)
window_turtle.pendown()
window_turtle.pensize(3)
window_turtle.pencolor("darkgreen")
window_turtle.fillcolor('red')
window_turtle.begin_fill()
window_turtle.goto(-100, -200)
window_turtle.goto(-100, -100)
window_turtle.goto(-200, -100)
window_turtle.goto(-200, -200)
window_turtle.end_fill()
window_turtle.penup()
window_turtle.goto(-150,-100)
window_turtle.pendown()
window_turtle.goto(-150,-200)
window_turtle.penup()
window_turtle.goto(-100,-150)
window_turtle.pendown()
window_turtle.goto(-200,-150)

#candycane on the tree
candy = turtle.Turtle()

candy.pensize(5)
candy.color("red")
candy.penup()
candy.goto(0, -100)
candy.pendown()
candy.setheading(90)
candy.forward(50)
candy.right(90)
candy.forward(10)
candy.right(90)
candy.forward(10)
candy.penup()
candy.goto(0, -100)
candy.pendown()
candy.end_fill()

#wreath next to the tree
t_wreath = turtle.Turtle()

t_wreath.penup()
t_wreath.goto(100,200)
t_wreath.hideturtle()
t_wreath.pencolor('black')
t_wreath.fillcolor('DarkGreen')
t_wreath.pendown()
t_wreath.begin_fill()
t_wreath.circle(50)
t_wreath.end_fill()

t_wreath.penup()
t_wreath.goto(100,220)
t_wreath.hideturtle()
t_wreath.pencolor('black')
t_wreath.fillcolor('wheat2')
t_wreath.pendown()
t_wreath.begin_fill()
t_wreath.circle(30)
t_wreath.end_fill()

#ornaments on the tree
t_ground.penup()
t_ground. goto(200,20)
t_ground.hideturtle()
t_ground.pencolor('lightpink')
t_ground.fillcolor('lightpink')
t_ground.pendown()
t_ground.begin_fill()
t_ground.circle(10)
t_ground.end_fill()
t_ground.pensize(4)
t_ground.penup()
t_ground. goto(170,-30)
t_ground.hideturtle()
t_ground.pencolor('red')
t_ground.fillcolor('blue')
t_ground.pendown()
t_ground.begin_fill()
t_ground.circle(15)
t_ground.end_fill()

t_ground.penup()
t_ground. goto(215,-50)
t_ground.hideturtle()
t_ground.pencolor('blue')
t_ground.fillcolor('red')
t_ground.pendown()
t_ground.begin_fill()
t_ground.circle(10)
t_ground.end_fill()

#words
message="Merry Christmas!"
t.goto(0,310)
t.color('red')
t.write(message,move=False,align='center',font=('Arilal',20,'bold'))



turtle.done()
